### ISSUE TITLE
Suggestion: Support unlink command

### ISSUE THREAD

**Issue by segevofer** [privatenumber/link#12]
Suggestion:
After running `npx link` support running `npx link --unlink` instead of running `npm i`

**Comment by privatenumber** [comment]
Sounds good to me. PR welcome!

**Comment by privatenumber** [comment]
Actually, there isn't much we can do on our end.

`npx link` isn't aware of the package manager being used and how `node_modules` is structured, so the most it can do is delete all symlinks in `node_modules`.

Deleting the symlinks will prevent the package from working expectedly, so the dev will have to run `npm install` anyway to fix the `node_modules`.
