### ISSUE TITLE
blog post linked in the README is 404

### ISSUE THREAD

**Issue by shazron** [privatenumber/link#8]
**404 url:**
https://hirok.io/posts/avoid-npm-link

**wayback machine:**
https://web.archive.org/web/20220422234748/https://hirok.io/posts/avoid-npm-link

**Suggestion:**
put the blog post as a Markdown file in this repo and link to it in the README, **OR** include the whole blog post in the README

**Comment by privatenumber** [comment]
URL works fine for me

**Comment by shazron** [comment]
No, just going to it from the browser. It was definitely down from Singapore for the period of 10 mins I tried. Maybe a cold start that never finished, who knows. It seems spun up now, works currently 👍🏼
